name: Go build and deploy

on:
  push:
    branches: [ main ]

jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Test
      run: go test -cover ./...

    - name: Build artifact
      run: |
        go build -v -o build/lambda github.com/mctofu/pushgate/cmd/lambda

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Set up SAM cli
      run: |
        python -m pip install --upgrade pip
        pip install aws-sam-cli

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy
      run: |
        cp template.yaml README.md LICENSE build/
        cd build
        sam package --s3-bucket ${{ secrets.SAM_S3_BUCKET }} --s3-prefix pushgate --output-template-file packaged-template.yaml
        sam publish --template-file packaged-template.yaml
